# Generated by Django 4.1 on 2023-05-14 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('matrial_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000, message='Value must be greater than or equal to 2000.'), django.core.validators.MaxValueValidator(6000, message='Value must be less than or equal to 6000.')])),
                ('date_of_birth', models.DateField()),
                ('vacation_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(10, message='Value must be less than or equal to 10.')])),
                ('aprroved_vacation_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1.'), django.core.validators.MaxValueValidator(10, message='Value must be less than or equal to 10.')])),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50)),
                ('Reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.employee')),
            ],
        ),
    ]
