# Generated by Django 4.1 on 2023-05-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='aprroved_vacation_number',
            new_name='approved_vacation_number',
        ),
    ]
