# Generated by Django 4.2 on 2023-05-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_employee_aprroved_vacation_number_and_more'),
        ('hr_app', '0002_rename_aprroved_vacation_number_employee_approved_vacation_number'),
    ]

    operations = [
    ]
