# Generated by Django 4.2 on 2023-05-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_remove_employee_approved_vacation_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='aprroved_vacation_number',
            new_name='approved_vacation_number',
        ),
    ]
