# Generated by Django 4.2 on 2023-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_rename_aprroved_vacation_number_employee_approved_vacation_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='approved_vacation_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='matrial_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vacation_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='approved_vacation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='material_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('widowed', 'widowed'), ('divorced', 'divorced'), ('separated', 'separated')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='vcation_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
