# Generated by Django 4.2 on 2023-05-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_alter_employee_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
