# Generated by Django 4.2 on 2023-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='emp_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
