# Generated by Django 4.2 on 2023-05-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_vacation_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='emp_Name',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='emp_id',
        ),
    ]
